spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/mxuser?autoReconnect=true&useUnicode=true&characterEncoding=utf8
    username: root
    password: root
    initialize: false


thrift:
  server:
    port: 8891
  client:
    applications:
      api: 127.0.0.1:8899